// <auto-generated />
using System;
using ArtDecoMebel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArtDecoMebel.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251215125246_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArtDecoMebel.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ArtDecoMebel.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "IKEA"
                        },
                        new
                        {
                            Id = 2,
                            Name = "JYSK"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Leroy Merlin"
                        },
                        new
                        {
                            Id = 4,
                            Name = "HomeMax"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Bauhaus"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Mr. Bricolage"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Praktiker"
                        });
                });

            modelBuilder.Entity("ArtDecoMebel.Models.Catalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Catalogs");
                });

            modelBuilder.Entity("ArtDecoMebel.Models.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Бял"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Черен"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Сив"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Червен"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Син"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Зелен"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Жълт"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Кафяв"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Оранжев"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Лилав"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Розов"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Бежов"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Други"
                        });
                });

            modelBuilder.Entity("ArtDecoMebel.Models.Furniture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<double>("Length")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductionYear")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<double>("Width")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("RoomId");

                    b.ToTable("Furnitures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 4,
                            Height = 100.8,
                            Length = 227.30000000000001,
                            Name = "Диван 'Виктория'",
                            Photo = "furniture1.png",
                            ProductionYear = 2018,
                            RoomId = 9,
                            Width = 120.3
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 7,
                            Height = 111.40000000000001,
                            Length = 288.69999999999999,
                            Name = "Маса 'Овал'",
                            Photo = "furniture2.png",
                            ProductionYear = 2016,
                            RoomId = 8,
                            Width = 63.799999999999997
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 1,
                            Height = 120.5,
                            Length = 100.09999999999999,
                            Name = "Стол 'Класик'",
                            Photo = "furniture3.png",
                            ProductionYear = 2021,
                            RoomId = 2,
                            Width = 60.100000000000001
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 6,
                            Height = 105.09999999999999,
                            Length = 230.09999999999999,
                            Name = "Легло 'Елеганс'",
                            Photo = "furniture4.png",
                            ProductionYear = 2022,
                            RoomId = 2,
                            Width = 110.5
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 1,
                            Height = 210.09999999999999,
                            Length = 150.5,
                            Name = "Секция 'Модерн'",
                            Photo = "furniture5.png",
                            ProductionYear = 2020,
                            RoomId = 4,
                            Width = 40.5
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 3,
                            Height = 75.0,
                            Length = 140.19999999999999,
                            Name = "Бюро 'Работно'",
                            Photo = "furniture6.png",
                            ProductionYear = 2024,
                            RoomId = 6,
                            Width = 70.099999999999994
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 5,
                            Height = 180.30000000000001,
                            Length = 80.0,
                            Name = "Шкаф 'Компакт'",
                            Photo = "furniture7.png",
                            ProductionYear = 2019,
                            RoomId = 7,
                            Width = 45.5
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 2,
                            Height = 110.09999999999999,
                            Length = 90.5,
                            Name = "Кресло 'Релакс'",
                            Photo = "furniture8.png",
                            ProductionYear = 2021,
                            RoomId = 1,
                            Width = 95.5
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 7,
                            Height = 60.0,
                            Length = 120.0,
                            Name = "Полица 'Минимал'",
                            Photo = "furniture9.png",
                            ProductionYear = 2022,
                            RoomId = 9,
                            Width = 25.0
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 1,
                            Height = 80.0,
                            Length = 80.0,
                            Name = "Огледало 'Кръг'",
                            Photo = "furniture10.png",
                            ProductionYear = 2023,
                            RoomId = 5,
                            Width = 3.0
                        },
                        new
                        {
                            Id = 11,
                            BrandId = 2,
                            Height = 45.0,
                            Length = 40.0,
                            Name = "Табуретка 'Пуф'",
                            Photo = "furniture11.png",
                            ProductionYear = 2024,
                            RoomId = 1,
                            Width = 40.0
                        },
                        new
                        {
                            Id = 12,
                            BrandId = 3,
                            Height = 220.0,
                            Length = 200.0,
                            Name = "Гардероб 'Сити'",
                            Photo = "furniture12.png",
                            ProductionYear = 2017,
                            RoomId = 2,
                            Width = 60.0
                        },
                        new
                        {
                            Id = 13,
                            BrandId = 4,
                            Height = 85.0,
                            Length = 100.0,
                            Name = "Кухненски шкаф",
                            Photo = "furniture13.png",
                            ProductionYear = 2020,
                            RoomId = 3,
                            Width = 50.0
                        },
                        new
                        {
                            Id = 14,
                            BrandId = 1,
                            Height = 100.0,
                            Length = 45.0,
                            Name = "Бар стол",
                            Photo = "furniture14.png",
                            ProductionYear = 2021,
                            RoomId = 3,
                            Width = 45.0
                        },
                        new
                        {
                            Id = 15,
                            BrandId = 5,
                            Height = 75.0,
                            Length = 160.0,
                            Name = "Трапезен комплект",
                            Photo = "furniture15.png",
                            ProductionYear = 2022,
                            RoomId = 4,
                            Width = 90.0
                        },
                        new
                        {
                            Id = 16,
                            BrandId = 6,
                            Height = 55.0,
                            Length = 50.0,
                            Name = "Нощно шкафче",
                            Photo = "furniture16.png",
                            ProductionYear = 2023,
                            RoomId = 2,
                            Width = 40.0
                        },
                        new
                        {
                            Id = 17,
                            BrandId = 7,
                            Height = 50.0,
                            Length = 180.0,
                            Name = "TV Шкаф",
                            Photo = "furniture17.png",
                            ProductionYear = 2019,
                            RoomId = 1,
                            Width = 45.0
                        },
                        new
                        {
                            Id = 18,
                            BrandId = 1,
                            Height = 45.0,
                            Length = 100.0,
                            Name = "Холна маса",
                            Photo = "furniture18.png",
                            ProductionYear = 2020,
                            RoomId = 1,
                            Width = 60.0
                        },
                        new
                        {
                            Id = 19,
                            BrandId = 2,
                            Height = 200.0,
                            Length = 80.0,
                            Name = "Библиотека",
                            Photo = "furniture19.png",
                            ProductionYear = 2021,
                            RoomId = 6,
                            Width = 30.0
                        },
                        new
                        {
                            Id = 20,
                            BrandId = 3,
                            Height = 180.0,
                            Length = 50.0,
                            Name = "Закачалка",
                            Photo = "furniture20.png",
                            ProductionYear = 2022,
                            RoomId = 9,
                            Width = 50.0
                        },
                        new
                        {
                            Id = 21,
                            BrandId = 4,
                            Height = 70.0,
                            Length = 140.0,
                            Name = "Градинска маса",
                            Photo = "furniture21.png",
                            ProductionYear = 2023,
                            RoomId = 8,
                            Width = 80.0
                        },
                        new
                        {
                            Id = 22,
                            BrandId = 5,
                            Height = 35.0,
                            Length = 190.0,
                            Name = "Шезлонг",
                            Photo = "furniture22.png",
                            ProductionYear = 2024,
                            RoomId = 8,
                            Width = 70.0
                        },
                        new
                        {
                            Id = 23,
                            BrandId = 6,
                            Height = 60.0,
                            Length = 160.0,
                            Name = "Детско легло",
                            Photo = "furniture23.png",
                            ProductionYear = 2020,
                            RoomId = 7,
                            Width = 80.0
                        },
                        new
                        {
                            Id = 24,
                            BrandId = 7,
                            Height = 80.0,
                            Length = 120.0,
                            Name = "Скрин",
                            Photo = "furniture24.png",
                            ProductionYear = 2021,
                            RoomId = 2,
                            Width = 45.0
                        },
                        new
                        {
                            Id = 25,
                            BrandId = 1,
                            Height = 120.0,
                            Length = 60.0,
                            Name = "Компютърен стол",
                            Photo = "furniture25.png",
                            ProductionYear = 2022,
                            RoomId = 6,
                            Width = 60.0
                        },
                        new
                        {
                            Id = 26,
                            BrandId = 2,
                            Height = 180.0,
                            Length = 80.0,
                            Name = "Офис шкаф",
                            Photo = "furniture26.png",
                            ProductionYear = 2023,
                            RoomId = 6,
                            Width = 40.0
                        },
                        new
                        {
                            Id = 27,
                            BrandId = 3,
                            Height = 85.0,
                            Length = 280.0,
                            Name = "Ъглов диван",
                            Photo = "furniture27.png",
                            ProductionYear = 2018,
                            RoomId = 1,
                            Width = 180.0
                        },
                        new
                        {
                            Id = 28,
                            BrandId = 4,
                            Height = 150.0,
                            Length = 100.0,
                            Name = "Рафт",
                            Photo = "furniture28.png",
                            ProductionYear = 2019,
                            RoomId = 9,
                            Width = 20.0
                        },
                        new
                        {
                            Id = 29,
                            BrandId = 5,
                            Height = 45.0,
                            Length = 120.0,
                            Name = "Пейка",
                            Photo = "furniture29.png",
                            ProductionYear = 2020,
                            RoomId = 8,
                            Width = 40.0
                        },
                        new
                        {
                            Id = 30,
                            BrandId = 6,
                            Height = 140.0,
                            Length = 90.0,
                            Name = "Тоалетка",
                            Photo = "furniture30.png",
                            ProductionYear = 2021,
                            RoomId = 2,
                            Width = 40.0
                        });
                });

            modelBuilder.Entity("ArtDecoMebel.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Materials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Дърво"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Метал"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Пластмаса"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Стъкло"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Текстил"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Кожа"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Мрамор"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Гранитогрес"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Други"
                        });
                });

            modelBuilder.Entity("ArtDecoMebel.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Всекидневна"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Спалня"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Кухня"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Трапезария"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Баня"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Офис"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Детска стая"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Градина"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Други"
                        });
                });

            modelBuilder.Entity("CatalogFurniture", b =>
                {
                    b.Property<int>("CatalogsId")
                        .HasColumnType("int");

                    b.Property<int>("FurnituresId")
                        .HasColumnType("int");

                    b.HasKey("CatalogsId", "FurnituresId");

                    b.HasIndex("FurnituresId");

                    b.ToTable("CatalogFurniture");
                });

            modelBuilder.Entity("ColorFurniture", b =>
                {
                    b.Property<int>("ColorsId")
                        .HasColumnType("int");

                    b.Property<int>("FurnituresId")
                        .HasColumnType("int");

                    b.HasKey("ColorsId", "FurnituresId");

                    b.HasIndex("FurnituresId");

                    b.ToTable("ColorFurniture");

                    b.HasData(
                        new
                        {
                            ColorsId = 12,
                            FurnituresId = 1
                        },
                        new
                        {
                            ColorsId = 8,
                            FurnituresId = 1
                        },
                        new
                        {
                            ColorsId = 1,
                            FurnituresId = 2
                        },
                        new
                        {
                            ColorsId = 8,
                            FurnituresId = 2
                        },
                        new
                        {
                            ColorsId = 2,
                            FurnituresId = 3
                        },
                        new
                        {
                            ColorsId = 3,
                            FurnituresId = 3
                        },
                        new
                        {
                            ColorsId = 1,
                            FurnituresId = 4
                        },
                        new
                        {
                            ColorsId = 12,
                            FurnituresId = 4
                        },
                        new
                        {
                            ColorsId = 8,
                            FurnituresId = 4
                        },
                        new
                        {
                            ColorsId = 8,
                            FurnituresId = 5
                        },
                        new
                        {
                            ColorsId = 3,
                            FurnituresId = 5
                        },
                        new
                        {
                            ColorsId = 3,
                            FurnituresId = 6
                        },
                        new
                        {
                            ColorsId = 1,
                            FurnituresId = 6
                        },
                        new
                        {
                            ColorsId = 12,
                            FurnituresId = 7
                        },
                        new
                        {
                            ColorsId = 8,
                            FurnituresId = 7
                        },
                        new
                        {
                            ColorsId = 1,
                            FurnituresId = 8
                        },
                        new
                        {
                            ColorsId = 12,
                            FurnituresId = 8
                        },
                        new
                        {
                            ColorsId = 3,
                            FurnituresId = 8
                        },
                        new
                        {
                            ColorsId = 12,
                            FurnituresId = 9
                        },
                        new
                        {
                            ColorsId = 8,
                            FurnituresId = 9
                        },
                        new
                        {
                            ColorsId = 1,
                            FurnituresId = 10
                        },
                        new
                        {
                            ColorsId = 11,
                            FurnituresId = 11
                        },
                        new
                        {
                            ColorsId = 1,
                            FurnituresId = 11
                        },
                        new
                        {
                            ColorsId = 12,
                            FurnituresId = 11
                        },
                        new
                        {
                            ColorsId = 3,
                            FurnituresId = 12
                        },
                        new
                        {
                            ColorsId = 1,
                            FurnituresId = 12
                        },
                        new
                        {
                            ColorsId = 2,
                            FurnituresId = 13
                        },
                        new
                        {
                            ColorsId = 8,
                            FurnituresId = 13
                        },
                        new
                        {
                            ColorsId = 3,
                            FurnituresId = 13
                        },
                        new
                        {
                            ColorsId = 8,
                            FurnituresId = 14
                        },
                        new
                        {
                            ColorsId = 1,
                            FurnituresId = 15
                        },
                        new
                        {
                            ColorsId = 3,
                            FurnituresId = 15
                        },
                        new
                        {
                            ColorsId = 12,
                            FurnituresId = 15
                        },
                        new
                        {
                            ColorsId = 3,
                            FurnituresId = 16
                        },
                        new
                        {
                            ColorsId = 12,
                            FurnituresId = 16
                        },
                        new
                        {
                            ColorsId = 8,
                            FurnituresId = 17
                        },
                        new
                        {
                            ColorsId = 1,
                            FurnituresId = 17
                        },
                        new
                        {
                            ColorsId = 3,
                            FurnituresId = 18
                        },
                        new
                        {
                            ColorsId = 1,
                            FurnituresId = 18
                        },
                        new
                        {
                            ColorsId = 5,
                            FurnituresId = 19
                        },
                        new
                        {
                            ColorsId = 3,
                            FurnituresId = 19
                        },
                        new
                        {
                            ColorsId = 12,
                            FurnituresId = 19
                        },
                        new
                        {
                            ColorsId = 1,
                            FurnituresId = 20
                        },
                        new
                        {
                            ColorsId = 8,
                            FurnituresId = 20
                        },
                        new
                        {
                            ColorsId = 3,
                            FurnituresId = 20
                        },
                        new
                        {
                            ColorsId = 12,
                            FurnituresId = 21
                        },
                        new
                        {
                            ColorsId = 1,
                            FurnituresId = 21
                        },
                        new
                        {
                            ColorsId = 12,
                            FurnituresId = 22
                        },
                        new
                        {
                            ColorsId = 5,
                            FurnituresId = 22
                        },
                        new
                        {
                            ColorsId = 3,
                            FurnituresId = 22
                        },
                        new
                        {
                            ColorsId = 12,
                            FurnituresId = 23
                        },
                        new
                        {
                            ColorsId = 1,
                            FurnituresId = 23
                        },
                        new
                        {
                            ColorsId = 11,
                            FurnituresId = 23
                        },
                        new
                        {
                            ColorsId = 8,
                            FurnituresId = 24
                        },
                        new
                        {
                            ColorsId = 12,
                            FurnituresId = 24
                        },
                        new
                        {
                            ColorsId = 2,
                            FurnituresId = 25
                        },
                        new
                        {
                            ColorsId = 3,
                            FurnituresId = 25
                        },
                        new
                        {
                            ColorsId = 1,
                            FurnituresId = 26
                        },
                        new
                        {
                            ColorsId = 8,
                            FurnituresId = 26
                        },
                        new
                        {
                            ColorsId = 12,
                            FurnituresId = 27
                        },
                        new
                        {
                            ColorsId = 1,
                            FurnituresId = 27
                        },
                        new
                        {
                            ColorsId = 3,
                            FurnituresId = 27
                        },
                        new
                        {
                            ColorsId = 8,
                            FurnituresId = 27
                        },
                        new
                        {
                            ColorsId = 1,
                            FurnituresId = 28
                        },
                        new
                        {
                            ColorsId = 12,
                            FurnituresId = 28
                        },
                        new
                        {
                            ColorsId = 8,
                            FurnituresId = 29
                        },
                        new
                        {
                            ColorsId = 12,
                            FurnituresId = 29
                        },
                        new
                        {
                            ColorsId = 12,
                            FurnituresId = 30
                        },
                        new
                        {
                            ColorsId = 1,
                            FurnituresId = 30
                        },
                        new
                        {
                            ColorsId = 3,
                            FurnituresId = 30
                        });
                });

            modelBuilder.Entity("FurnitureMaterial", b =>
                {
                    b.Property<int>("FurnituresId")
                        .HasColumnType("int");

                    b.Property<int>("MaterialsId")
                        .HasColumnType("int");

                    b.HasKey("FurnituresId", "MaterialsId");

                    b.HasIndex("MaterialsId");

                    b.ToTable("FurnitureMaterial");

                    b.HasData(
                        new
                        {
                            FurnituresId = 1,
                            MaterialsId = 5
                        },
                        new
                        {
                            FurnituresId = 1,
                            MaterialsId = 1
                        },
                        new
                        {
                            FurnituresId = 2,
                            MaterialsId = 1
                        },
                        new
                        {
                            FurnituresId = 2,
                            MaterialsId = 2
                        },
                        new
                        {
                            FurnituresId = 2,
                            MaterialsId = 7
                        },
                        new
                        {
                            FurnituresId = 3,
                            MaterialsId = 3
                        },
                        new
                        {
                            FurnituresId = 3,
                            MaterialsId = 2
                        },
                        new
                        {
                            FurnituresId = 4,
                            MaterialsId = 1
                        },
                        new
                        {
                            FurnituresId = 4,
                            MaterialsId = 9
                        },
                        new
                        {
                            FurnituresId = 5,
                            MaterialsId = 1
                        },
                        new
                        {
                            FurnituresId = 6,
                            MaterialsId = 1
                        },
                        new
                        {
                            FurnituresId = 6,
                            MaterialsId = 2
                        },
                        new
                        {
                            FurnituresId = 6,
                            MaterialsId = 4
                        },
                        new
                        {
                            FurnituresId = 7,
                            MaterialsId = 7
                        },
                        new
                        {
                            FurnituresId = 7,
                            MaterialsId = 1
                        },
                        new
                        {
                            FurnituresId = 8,
                            MaterialsId = 1
                        },
                        new
                        {
                            FurnituresId = 8,
                            MaterialsId = 6
                        },
                        new
                        {
                            FurnituresId = 9,
                            MaterialsId = 1
                        },
                        new
                        {
                            FurnituresId = 9,
                            MaterialsId = 5
                        },
                        new
                        {
                            FurnituresId = 10,
                            MaterialsId = 4
                        },
                        new
                        {
                            FurnituresId = 10,
                            MaterialsId = 3
                        },
                        new
                        {
                            FurnituresId = 11,
                            MaterialsId = 5
                        },
                        new
                        {
                            FurnituresId = 11,
                            MaterialsId = 1
                        },
                        new
                        {
                            FurnituresId = 12,
                            MaterialsId = 1
                        },
                        new
                        {
                            FurnituresId = 13,
                            MaterialsId = 1
                        },
                        new
                        {
                            FurnituresId = 13,
                            MaterialsId = 2
                        },
                        new
                        {
                            FurnituresId = 13,
                            MaterialsId = 6
                        },
                        new
                        {
                            FurnituresId = 14,
                            MaterialsId = 6
                        },
                        new
                        {
                            FurnituresId = 14,
                            MaterialsId = 2
                        },
                        new
                        {
                            FurnituresId = 15,
                            MaterialsId = 1
                        },
                        new
                        {
                            FurnituresId = 15,
                            MaterialsId = 4
                        },
                        new
                        {
                            FurnituresId = 15,
                            MaterialsId = 8
                        },
                        new
                        {
                            FurnituresId = 16,
                            MaterialsId = 1
                        },
                        new
                        {
                            FurnituresId = 16,
                            MaterialsId = 3
                        },
                        new
                        {
                            FurnituresId = 17,
                            MaterialsId = 1
                        },
                        new
                        {
                            FurnituresId = 17,
                            MaterialsId = 2
                        },
                        new
                        {
                            FurnituresId = 18,
                            MaterialsId = 1
                        },
                        new
                        {
                            FurnituresId = 18,
                            MaterialsId = 9
                        },
                        new
                        {
                            FurnituresId = 19,
                            MaterialsId = 5
                        },
                        new
                        {
                            FurnituresId = 19,
                            MaterialsId = 1
                        },
                        new
                        {
                            FurnituresId = 20,
                            MaterialsId = 1
                        },
                        new
                        {
                            FurnituresId = 20,
                            MaterialsId = 2
                        },
                        new
                        {
                            FurnituresId = 21,
                            MaterialsId = 1
                        },
                        new
                        {
                            FurnituresId = 21,
                            MaterialsId = 8
                        },
                        new
                        {
                            FurnituresId = 22,
                            MaterialsId = 6
                        },
                        new
                        {
                            FurnituresId = 22,
                            MaterialsId = 1
                        },
                        new
                        {
                            FurnituresId = 23,
                            MaterialsId = 1
                        },
                        new
                        {
                            FurnituresId = 23,
                            MaterialsId = 5
                        },
                        new
                        {
                            FurnituresId = 24,
                            MaterialsId = 1
                        },
                        new
                        {
                            FurnituresId = 25,
                            MaterialsId = 2
                        },
                        new
                        {
                            FurnituresId = 25,
                            MaterialsId = 3
                        },
                        new
                        {
                            FurnituresId = 26,
                            MaterialsId = 2
                        },
                        new
                        {
                            FurnituresId = 26,
                            MaterialsId = 1
                        },
                        new
                        {
                            FurnituresId = 27,
                            MaterialsId = 5
                        },
                        new
                        {
                            FurnituresId = 27,
                            MaterialsId = 1
                        },
                        new
                        {
                            FurnituresId = 27,
                            MaterialsId = 2
                        },
                        new
                        {
                            FurnituresId = 28,
                            MaterialsId = 1
                        },
                        new
                        {
                            FurnituresId = 28,
                            MaterialsId = 4
                        },
                        new
                        {
                            FurnituresId = 29,
                            MaterialsId = 1
                        },
                        new
                        {
                            FurnituresId = 29,
                            MaterialsId = 7
                        },
                        new
                        {
                            FurnituresId = 30,
                            MaterialsId = 1
                        },
                        new
                        {
                            FurnituresId = 30,
                            MaterialsId = 6
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ArtDecoMebel.Models.Catalog", b =>
                {
                    b.HasOne("ArtDecoMebel.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("Catalogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("ArtDecoMebel.Models.Furniture", b =>
                {
                    b.HasOne("ArtDecoMebel.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArtDecoMebel.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("CatalogFurniture", b =>
                {
                    b.HasOne("ArtDecoMebel.Models.Catalog", null)
                        .WithMany()
                        .HasForeignKey("CatalogsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArtDecoMebel.Models.Furniture", null)
                        .WithMany()
                        .HasForeignKey("FurnituresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ColorFurniture", b =>
                {
                    b.HasOne("ArtDecoMebel.Models.Color", null)
                        .WithMany()
                        .HasForeignKey("ColorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArtDecoMebel.Models.Furniture", null)
                        .WithMany()
                        .HasForeignKey("FurnituresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FurnitureMaterial", b =>
                {
                    b.HasOne("ArtDecoMebel.Models.Furniture", null)
                        .WithMany()
                        .HasForeignKey("FurnituresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArtDecoMebel.Models.Material", null)
                        .WithMany()
                        .HasForeignKey("MaterialsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ArtDecoMebel.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ArtDecoMebel.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArtDecoMebel.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ArtDecoMebel.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ArtDecoMebel.Models.ApplicationUser", b =>
                {
                    b.Navigation("Catalogs");
                });
#pragma warning restore 612, 618
        }
    }
}
